language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy etsh2o/reverseproxy:v2 
  - docker tag udagram-frontend:local etsh2o/udagram-frontend:v2 
  - docker tag udagram-api-feed etsh2o/udagram-api-feed:v2 
  - docker tag udagram-api-user etsh2o/udagram-api-user:v2 

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push etsh2o/reverseproxy:v2
  - docker push etsh2o/udagram-frontend:v2
  - docker push etsh2o/udagram-api-feed:v2
  - docker push etsh2o/udagram-api-user:v2
 
